### ISSUE TITLE
ld-decode-detect:  extremely rotted disks still produce .json files too large for Qt.

### ISSUE THREAD

**Issue by happycube** [happycube/ld-decode#108]
My copy of Erica (where most fields have >10 dropouts, and for a bit of the disk every other field has >100) produced too many for the current tools to handle.

**Comment by simoninns** [comment]
Although ld-decode-detect will be removed before rev4 release, this issue will still cause problems with the tools in general.  If Qt patches the silly 128Mb JSON limit this will go away; otherwise a new JSON library is going to have to be included.  Since this is an edge-case, it can go in rev5

**Comment by Gamnn** [comment]
QT bug tracker on the limit: https://bugreports.qt.io/browse/QTBUG-47629

**Comment by simoninns** [comment]
The ld-decode-shared library has been ported to the JsonWax library (which is GPL):

https://github.com/doublejim/JsonWax

JSON output is now dynamically created, so the only failure should be if the QVectors used to store the metadata internally fail to allocate (due to insufficient local RAM/heap).

Be cautious to back up JSON files produced by ld-decode before testing the new library functions in the latest commit.

I'll leave this report open for a couple of days just in case there are any issues with the new library.

**Comment by IanSmallshire** [comment]
Tested with two large JSON files
1) 326.7 MB (326,730,812 bytes) 
All seems OK

2) 1.1 GB (1,145,055,213 bytes) 
UI fails to load and then exits with following error:

```
ian@DDDcap:~/ldd-rev4/ld-decode/tools/ld-analyse$ ./ld-analyse 
Gtk-Message: 20:57:54.831: GtkDialog mapped without a transient parent. This is discouraged.
Info: Opening TBC filename = "/home/ian/GardenBirds_CAV_PAL_side2_Teletext_2018-10-10_10-30-32_100.tbc"
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

```
Running on i5 with 8GB RAM

**Comment by simoninns** [comment]
As long as it fails with a bad_alloc; it's working properly - that's your machine running out of heap space for the process.   The fact that it handles more than double the previous limit is a bonus :)
