### ISSUE TITLE
FDLS implementation appears to be incorrect

### ISSUE THREAD

**Issue by nathanielatom** [happycube/ld-decode#159]
I think several invocations of scipy's `freqz` should actually be calling `freqs`. For example on this line which passes analog filter coefficients: https://github.com/happycube/ld-decode/blob/a9418b96a492ca6b6d6b0bab33a244b371e5e348/fdls.py#L143

**Comment by happycube** [comment]
Right now it's not being called by anything, but I've added an analog option to rev5.

For most other uses in ld-decode it should be freqz, since they are producing digital filters.  It's possible that some filters might gain from being done analog style, so I'll probably add a path for that and leave this open for now...
