### ISSUE TITLE
Luma mode blurry compared to source, chroma

### ISSUE THREAD

**Issue by Gamnn** [happycube/ld-decode#347]
The filter for luma seems to need some adjustment, it's blurry compared to the ntsc comb output.

Frame 18746 from ggv-1069:

![frame_ntsc_source_18746](https://user-images.githubusercontent.com/44366267/68528747-35927a80-033a-11ea-9ae0-0e442b4c70ea.png)
![frame_ntsc_comb_18746](https://user-images.githubusercontent.com/44366267/68528749-39260180-033a-11ea-8485-6c24b9711787.png)
![frame_ntsc_luma_18746](https://user-images.githubusercontent.com/44366267/68528751-3c20f200-033a-11ea-8cbc-1a9f0120af22.png)

**Comment by simoninns** [comment]
As mentioned on IRC, the luma mode in ld-analyse isn't using the comb filter and is there to help with development (of things like the diffdod tool).  It might be possible to make the filter a little sharper, but there is no need for it since the ld-chroma-decoder has a really good B&W mode for actual video output

**Comment by atsampson** [comment]
It might be better to call that mode "LPF" rather than "Luma"? It's never going to look particularly sharp, even if the cutoff is made sharper, because the idea is to remove the HF content (which includes both noise and legitimate sharp edges).

**Comment by simoninns** [comment]
Re-opening issue - Agreed that the Luma mode should be renamed to save confusion.  I'll fix it and then close this issue.

**Comment by simoninns** [comment]
Fixed in latest commit.
