### ISSUE TITLE
NTSC chroma post-filter available in ld-analyse, but not ld-chroma-decoder

### ISSUE THREAD

**Issue by happycube** [happycube/ld-decode#700]
ImminentTax pointed this out to me in a DM on Discord - This is mostly a matter of the command line option not being implemented, I think.

**Comment by atsampson** [comment]
I hadn't added it because the option isn't really useful - in a hardware decoder it would be necessary to remove the high-frequency aliases of the chroma signal after downconversion, but the decoder in Comb.cpp uses an approach that doesn't produce aliases in the first place (it's like a software version of a Tayloe mixer). The PAL decoder uses a conventional mixer so it does need a post-filter.
