### ISSUE TITLE
Stop decoding at lead-out code by default?

### ISSUE THREAD

**Issue by happycube** [happycube/ld-decode#82]
Related to bug #56, a better default would be stopping when the lead-out code is seen.  The ? is because players may immediately seek at that point before a complete field with said code is read.

**Comment by simoninns** [comment]
Probably related to #83 too.

**Comment by simoninns** [comment]
Thinking about this I'd say that "stop on lead-out" should be optional.  The default should be to stop when there is no more data to process.  Otherwise ld-decode is assuming a detail about the source tbc (based on a player's reaction to the end of disc) which might not be a good assumption as there are a lot of players out there :)
